# Generated by Django 4.2.7 on 2023-11-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgOszczednosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osczednosc_calkowita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bgkategoria',
            name='budzet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budgetApp.bgbudzet'),
        ),
        migrations.AlterField(
            model_name='bgbudzet',
            name='budzet_wartosc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bgkategoria',
            name='kategoria_nazwa',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='bgkategoria',
            name='kategoria_wydatek',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bgwydatek',
            name='wydatek_warotsc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='BgPolaczenie',
        ),
        migrations.AddField(
            model_name='bgoszczednosc',
            name='budzet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.bgbudzet'),
        ),
    ]
