# Generated by Django 4.2.7 on 2023-11-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0002_bgoszczednosc_bgkategoria_budzet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgbudzet',
            old_name='budrzet_miesiac',
            new_name='budzet_miesiac',
        ),
    ]
