# Generated by Django 4.2.7 on 2023-11-30 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0003_rename_budrzet_miesiac_bgbudzet_budzet_miesiac'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgwydatek',
            name='wydatek_budzet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wydatek', to='budgetApp.bgbudzet'),
        ),
    ]
