# Generated by Django 4.1.5 on 2023-12-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0004_bgwydatek_wydatek_budzet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgwydatek',
            old_name='wydatek_warotsc',
            new_name='wydatek_wartosc',
        ),
        migrations.AlterField(
            model_name='bgwydatek',
            name='wydatek_data',
            field=models.DateField(auto_now=True),
        ),
    ]
